### ISSUE TITLE
Build and run errors

### ISSUE THREAD

**Issue by hariseldon78** [rianadon/Cosmos-Keyboards#31]
Hi, I'm trying to run the application locally because I want to add a 128x64 display. 
During the `make quickstart` I get this error: 
```
[...]
[2s] Generating 1.5u r3 mt3
[2s] Generating 1.5u r4 mt3
[2s] Generating 1.5u r5 mt3
[1s] Generating 2u r0 mt3
[1s] Generating 2u r1 mt3
[1s] Generating 2u r2 mt3
[1s] Generating 2u r3 mt3
[1s] Generating 2u r4 mt3
[1s] Generating 2u r5 mt3
Plus 96 more tasks
43 |     cp.send(this.taskReference!.indexOf(item))
44 |     return {
45 |       name: item.name,
46 |       promise: new Promise<R>((resolve, reject) => {
47 |         cp.once('message', (m: any) => {
48 |           if (m.error) reject(new Error(m.error))
                                   ^
error: Out of bounds memory access (evaluating 'entryFunction(argc, argv)')
      at /home/roby/Developer/opensource/Cosmos-Keyboards/src/model_gen/processPool.ts:48:31
      at onceWrapper (node:events:37:21)
      at emit (node:events:201:48)
      at #emitIpcMessage (node:child_process:804:18)

Bun v1.1.27 (Linux x64)
make: *** [Makefile:48: keycaps2] Error 1

```

and then, during the `make dev` i get this error reported in the browser:
```
[plugin:vite:import-analysis] Failed to resolve import "../../../target/sockets-simple.json" from "src/lib/loaders/simpleparts.ts". Does the file exist?

/home/roby/Developer/opensource/Cosmos-Keyboards/src/lib/loaders/simpleparts.ts:5:20

1  |  import { BufferGeometry, Group, Matrix4, Triangle, Vector3 } from "three";
2  |  import { STLLoader } from "three/examples/jsm/loaders/STLLoader";
3  |  import sockets from "../../../target/sockets-simple.json";
   |                       ^
4  |  import { ITriangle } from "./simplekeys";
5  |  function socket(name) {

    at TransformPluginContext._formatError (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:49746:41)
    at TransformPluginContext.error (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:49741:16)
    at normalizeUrl (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:64331:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:64463:39
    at async Promise.all (index 2)
    at async TransformPluginContext.transform (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:64390:7)
    at async PluginContainer.transform (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:49587:18)
    at async loadAndTransform (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:52409:27)
    at async viteTransformMiddleware (file:///home/roby/Developer/opensource/Cosmos-Keyboards/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:62173:24

```

I'm using arch linux (btw) and bun 1.1.27.

**Comment by rianadon** [comment]
Hey. For some reason bun has been struggling with the wasm libraries. I've noticed this error appears randomly, and if you repeatedly run things eventually they'll work.

Node.js is also a lot more solid with these scripts for some reason. A `make BUN= quickstart` should work.

**Comment by finn-e** [comment]
Used make BUN= quickstart is still giving errors. It does make it past the our of bounds memory access error, but fails with a bunch of:

Node.js v23.9.0
file:///home/fin/kitchen/Cosmos-Keyboards/src/assets/replicad_single.js:51
                throw ex;
                ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:753:16)
    at queue.<computed>.f.then.process.send.id (file:///home/fin/kitchen/Cosmos-Keyboards/src/model_gen/processPool.ts:68:63)
Emitted 'error' event on process instance at:
    at node:internal/child_process:757:35
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
-----
I'm getting a very similar error when running 'make parts' with or without BUN= in the docker container. I've added a display and need it to generate the .glb file, but this happens a bunch:

Node.js v21.5.0
file:///Cosmos-Keyboards/src/assets/replicad_single.js:51
                throw ex;
                ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at queue.<computed>.f.then.process.send.id (file:///Cosmos-Keyboards/src/model_gen/processPool.ts:68:63)
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
-----
I think it is happening in the general docker-compose up as well, as pulling up a keyboard with trackball in the Cosmos Keyboard Configurator give the following:
There are some rough edges in this tool, and you've found one of them.

The set of options you've chosen cannot be previewed.

Here's some technical information:

During processing of Preview

Error: Model for url /target/socket-trackball-55mm-ball-skree-zmk.glb does not exist
Error: Model for url /target/socket-trackball-55mm-ball-skree-zmk.glb does not exist at http://localhost:5173/src/lib/loaders/gltfLoader.ts?t=1747056854990:13:25 at http://localhost:5173/src/lib/loaders/cacher.ts:11:41 at loadGLTF (http://localhost:5173/src/lib/loaders/gltfLoader.ts?t=1747056854990:17:10) at http://localhost:5173/src/lib/loaders/sockets.ts?t=1747056854990:59:17
------
It is hung at 'Generating: 10%'. This was gotten when running it with docker-compose up.

**Comment by finn-e** [comment]
I didn't want to edit since I'd already @'d people and wasn't sure what that would do.
I've managed to get past that error somehow and finish. However, I get a bunch of these errors:
Warning: could not generate trackball-25mm-roller-joe-qmk since its file was not present in the filesystem
This is OK as long as the models you generate do not include this part.
-----
There are errors for every variety of trackball.
Maybe src/model_gen/parametric/trackball-gen.ts is not getting ran?

**Comment by rianadon** [comment]
I had mistakenly pushed my version of `parts.ts` with the trackball stuff commented out. I did this locally because trackball generation takes forever, but I have new version of `parts.ts` that only regenerates modified parts I will push soon.

Any idea why you were seeing the
```
file:///home/fin/kitchen/Cosmos-Keyboards/src/assets/replicad_single.js:51
throw ex;
```
errors?

Were you able to fix these?

**Comment by finn-e** [comment]
I made it past it by chmod'ing everying 777 and chown'ing it to my user. I think things got wonky when I started going back and forth between docker and regular, trying to get either to work. Both now work with the fixed permissions.
